
import * as THREE from 'three';
import { AirfoilParams } from '../types';
import { generateNACAShape, generateFreeformShape } from './naca';

export const exportToOBJ = (params: AirfoilParams): void => {
  // 1. Generate the 2D Shape
  let shape: THREE.Shape;
  if (params.mode === 'freeform') {
    shape = generateFreeformShape(params.controlPoints);
  } else {
    shape = generateNACAShape(params.camber, params.position, params.thickness);
  }

  // 2. Get Points from Shape
  // Use a high division count for smoothness
  const points2D = shape.getPoints(50);
  
  // 3. Extrude Logic (Manual OBJ generation for simplicity without Three.js exporter dependency in strict mode)
  // We create a mesh with depth 4 (matching the scene)
  const depth = 4;
  const zFront = depth / 2;
  const zBack = -depth / 2;

  let objContent = `# Aerodynamic Spoiler Export\n`;
  objContent += `# Generated by AeroFlow Viz\n`;
  objContent += `o Spoiler\n`;

  // Vertices
  // We need two sets of vertices: Front face and Back face
  // Index starts at 1 in OBJ
  
  // Front Face (Z+)
  points2D.forEach(p => {
    objContent += `v ${p.x} ${p.y} ${zFront}\n`;
  });

  // Back Face (Z-)
  points2D.forEach(p => {
    objContent += `v ${p.x} ${p.y} ${zBack}\n`;
  });

  // Faces
  const len = points2D.length; // Number of points in the loop
  // OBJ indices are 1-based
  
  // Front Cap (Polygon)
  objContent += `f`;
  for (let i = 0; i < len; i++) {
    objContent += ` ${i + 1}`;
  }
  objContent += `\n`;

  // Back Cap (Polygon) - Reversed order for correct normal
  objContent += `f`;
  for (let i = 0; i < len; i++) {
    objContent += ` ${len + len - i}`;
  }
  objContent += `\n`;

  // Side Walls (Quads connecting front and back)
  // Connect i (front), i+1 (front), i+1 (back), i (back)
  // Note: points2D usually closes the loop (last point == first point)
  // If so, we iterate len-1. Let's check.
  // THREE.Shape.getPoints() includes the start point at the end if closed.
  
  for (let i = 0; i < len - 1; i++) {
    const v1 = i + 1;           // Front current
    const v2 = i + 2;           // Front next
    const v3 = len + i + 2;     // Back next
    const v4 = len + i + 1;     // Back current
    
    objContent += `f ${v1} ${v4} ${v3} ${v2}\n`;
  }

  // Create Blob and Download
  const blob = new Blob([objContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `spoiler_${params.mode}_${Date.now()}.obj`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
